// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://raeateoobiztkzpppvas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZWF0ZW9vYml6dGt6cHBwdmFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjI2MDksImV4cCI6MjA2NTU5ODYwOX0.6X2-4MY0RqH9qV8dGbdij2Mx1u1MUwP2E29rjXZbc-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);